const appointmentsTypes = {

    CREATE_APPOINTMENT_START: 'CREATE_APPOINTMENT_START',
    CREATE_APPOINTMENT_SUCCESS: 'CREATE_APPOINTMENT_SUCCESS',
    CREATE_APPOINTMENT_FAILURE: 'CREATE_APPOINTMENT_FAILURE',

    DELETE_APPOINTMENT_START: 'DELETE_APPOINTMENT_START',
    DELETE_APPOINTMENT_SUCCESS: 'DELETE_APPOINTMENT_SUCCESS',
    DELETE_APPOINTMENT_FAILURE: 'DELETE_APPOINTMENT_FAILURE',

    EDIT_APPOINTMENT_START: 'EDIT_APPOINTMENT_START',
    EDIT_APPOINTMENT_SUCCESS: 'EDIT_APPOINTMENT_SUCCESS',
    EDIT_APPOINTMENT_FAILURE: 'EDIT_APPOINTMENT_FAILURE',

    FETCH_APPOINTMENTS_START: 'FETCH_APPOINTMENTS_START',
    FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',
    FETCH_APPOINTMENTS_FAILURE: 'FETCH_APPOINTMENTS_FAILURE',

    FETCH_APPOINTMENTS_DATES_START: 'FETCH_APPOINTMENTS_DATES_START',
    FETCH_APPOINTMENTS_DATES_SUCCESS: 'FETCH_APPOINTMENTS_DATES_SUCCESS',
    FETCH_APPOINTMENTS_DATES_FAILURE: 'FETCH_APPOINTMENTS_DATES_FAILURE',


    CHOOSE_APPOINTMENT: 'CHOOSE_APPOINTMENT',
    CLEAR_CHOSEN_APPOINTMENT: 'CLEAR_CHOSEN_APPOINTMENT',

    FETCH_SPECIALISTS_START: 'FETCH_SPECIALISTS_START',
    FETCH_SPECIALISTS_SUCCESS: 'FETCH_SPECIALISTS_SUCCESS',
    FETCH_SPECIALISTS_FAILURE: 'FETCH_SPECIALISTS_FAILURE',

    FETCH_ROOMS_START: 'FETCH_ROOMS_START',
    FETCH_ROOMS_SUCCESS: 'FETCH_ROOMS_SUCCESS',
    FETCH_ROOMS_FAILURE: 'FETCH_ROOMS_FAILURE',
};

export default appointmentsTypes;