const lkRegionalActionTypes = {

    EDIT_FORM: 'EDIT_FORM',

    FETCH_MUNICIPAL_DISTRICTS_START: 'FETCH_MUNICIPAL_DISTRICTS_START',
    FETCH_MUNICIPAL_DISTRICTS_SUCCESS: 'FETCH_MUNICIPAL_DISTRICTS_SUCCESS',
    FETCH_MUNICIPAL_DISTRICTS_FAILURE: 'FETCH_MUNICIPAL_DISTRICTS_FAILURE',

    CREATE_MUNICIPALITY_START: 'CREATE_MUNICIPALITY_START',
    CREATE_MUNICIPALITY_SUCCESS: 'CREATE_MUNICIPALITY_SUCCESS',
    CREATE_MUNICIPALITY_FAILURE: 'CREATE_MUNICIPALITY_FAILURE',

    DELETE_MUNICIPALITY_START: 'DELETE_MUNICIPALITY_START',
    DELETE_MUNICIPALITY_SUCCESS: 'DELETE_MUNICIPALITY_SUCCESS',
    DELETE_MUNICIPALITY_FAILURE: 'DELETE_MUNICIPALITY_FAILURE',



    FETCH_MUNICIPAL_DATA_START: 'FETCH_MUNICIPAL_DATA_START',
    FETCH_MUNICIPAL_DATA_SUCCESS: 'FETCH_MUNICIPAL_DATA_SUCCESS',
    FETCH_MUNICIPAL_DATA_FAILURE: 'FETCH_MUNICIPAL_DATA_FAILURE',

    MUNICIPALITY_SELECT_CONFIRM: 'MUNICIPALITY_SELECT_CONFIRM',

    EDIT_MUNICIPALITY_DATA_START: 'EDIT_MUNICIPALITY_DATA_START',
    EDIT_MUNICIPALITY_DATA_SUCCESS: 'EDIT_MUNICIPALITY_DATA_SUCCESS',
    EDIT_MUNICIPALITY_DATA_FAILURE: 'EDIT_MUNICIPALITY_DATA_FAILURE',

};

export default lkRegionalActionTypes;