const childrenActionTypes = {
    FETCH_CHILDREN_START: 'FETCH_CHILDREN_START',
    FETCH_CHILDREN_SUCCESS: 'FETCH_CHILDREN_SUCCESS',
    FETCH_CHILDREN_FAILURE: 'FETCH_CHILDREN_FAILURE',
    SET_CHILDREN_QUERY: 'SET_CHILDREN_QUERY'
};

export default childrenActionTypes;
