const adminPagesTypes = {
    FETCH_FAQ_START: 'FETCH_FAQ_ADMIN_START',
    FETCH_FAQ_SUCCESS: 'FETCH_FAQ_ADMIN_SUCCESS',
    FETCH_FAQ_FAILURE: 'FETCH_FAQ_ADMIN_FAILURE',

    ADD_FAQ_QUESTION_START: 'ADD_FAQ_QUESTION_START',
    ADD_FAQ_QUESTION_SUCCESS: 'ADD_FAQ_QUESTION_SUCCESS',
    ADD_FAQ_QUESTION_FAILURE: 'ADD_FAQ_QUESTION_FAILURE',

    DELETE_FAQ_QUESTION_START: 'DELETE_FAQ_QUESTION_START',
    DELETE_FAQ_QUESTION_SUCCESS: 'DELETE_FAQ_QUESTION_SUCCESS',
    DELETE_FAQ_QUESTION_FAILURE: 'DELETE_FAQ_QUESTION_FAILURE',

    EDIT_FAQ_QUESTION_START: 'EDIT_FAQ_QUESTION_START',
    EDIT_FAQ_QUESTION_SUCCESS: 'EDIT_FAQ_QUESTION_SUCCESS',
    EDIT_FAQ_QUESTION_FAILURE: 'EDIT_FAQ_QUESTION_FAILURE',

    FETCH_DOCUMENT_TYPES_START: 'FETCH_DOCUMENT_TYPES_START',
    FETCH_DOCUMENT_TYPES_SUCCESS: 'FETCH_DOCUMENT_TYPES_SUCCESS',
    FETCH_DOCUMENT_TYPES_FAILURE: 'FETCH_DOCUMENT_TYPES_FAILURE',

    FETCH_INTER_LAW_FILES_START: 'FETCH_INTER_LAW_FILES_START',
    FETCH_INTER_LAW_FILES_SUCCESS: 'FETCH_INTER_LAW_FILES_SUCCESS',
    FETCH_INTER_LAW_FILES_FAILURE: 'FETCH_INTER_LAW_FILES_FAILURE',

    SUBMIT_INTER_LAW_FILE_START: 'SUBMIT_INTER_LAW_FILE_START',
    SUBMIT_INTER_LAW_FILE_SUCCESS: 'SUBMIT_INTER_LAW_FILE_SUCCESS',
    SUBMIT_INTER_LAW_FILE_FAILURE: 'SUBMIT_INTER_LAW_FILE_FAILURE',

    DELETE_INTER_LAW_FILE_START: 'DELETE_INTER_LAW_FILE_START',
    DELETE_INTER_LAW_FILE_SUCCESS: 'DELETE_INTER_LAW_FILE_SUCCESS',
    DELETE_INTER_LAW_FILE_FAILURE: 'DELETE_INTER_LAW_FILE_FAILURE',

    EDIT_INTER_LAW_FILE_START: 'EDIT_INTER_LAW_FILE_START',
    EDIT_INTER_LAW_FILE_SUCCESS: 'EDIT_INTER_LAW_FILE_SUCCESS',
    EDIT_INTER_LAW_FILE_FAILURE: 'EDIT_INTER_LAW_FILE_FAILURE',

    FETCH_ADMIN_CONTACTS_START: 'FETCH_ADMIN_CONTACTS_START',
    FETCH_ADMIN_CONTACTS_SUCCESS: 'FETCH_ADMIN_CONTACTS_SUCCESS',
    FETCH_ADMIN_CONTACTS_FAILURE: 'FETCH_ADMIN_CONTACTS_FAILURE',
    
    SUBMIT_CONTACTS_ADMIN_START: 'SUBMIT_CONTACTS_ADMIN_START',
    SUBMIT_CONTACTS_ADMIN_SUCCESS: 'SUBMIT_CONTACTS_ADMIN_SUCCESS',
    SUBMIT_CONTACTS_ADMIN_FAILURE: 'SUBMIT_INTER_LAW_FILE_FAILURE',
    
    ADD_NEWS_ADMIN_START: 'ADD_NEWS_ADMIN_START',
    ADD_NEWS_ADMIN_SUCCESS: 'ADD_NEWS_ADMIN_SUCCESS',
    ADD_NEWS_ADMIN_FAILURE: 'ADD_NEWS_ADMIN_FAILURE',
    
    DELETE_NEWS_ADMIN_START: 'DELETE_NEWS_ADMIN_START',
    DELETE_NEWS_ADMIN_SUCCESS: 'DELETE_NEWS_ADMIN_SUCCESS',
    DELETE_NEWS_ADMIN_FAILURE: 'DELETE_NEWS_ADMIN_FAILURE',
    
    
    
};

export default adminPagesTypes;