const adminUsersTypes = {
    FETCH_USERS_ADMIN_START: 'FETCH_USERS_ADMIN_START',
    FETCH_USERS_ADMIN_SUCCESS: 'FETCH_USERS_ADMIN_SUCCESS',
    FETCH_USERS_ADMIN_FAILURE: 'FETCH_USERS_ADMIN_FAILURE',
    
    FILTER_USER_ROLE: 'FILTER_USER_ROLE',
    FILTER_SEARCH_QUERY: 'FILTER_SEARCH_QUERY',
    SELECT_USER: 'SELECT_USER',
    EDIT_USER: 'EDIT_USER',
    
    SUBMIT_USER_EDITION_START:'SUBMIT_USER_EDITION_START',
    SUBMIT_USER_EDITION_SUCCESS:'SUBMIT_USER_EDITION_SUCCESS',
    SUBMIT_USER_EDITION_FAILURE:'SUBMIT_USER_EDITION_FAILURE',
};

export default adminUsersTypes;