const appointmentActionTypes = {
    FETCH_DATES_START: 'FETCH_DATES_START',
    FETCH_DATES_SUCCESS: 'FETCH_DATES_SUCCESS',
    FETCH_DATES_FAILURE: 'FETCH_DATES_FAILURE',

    FETCH_TIME_START: 'FETCH_TIME_START',
    FETCH_TIME_SUCCESS: 'FETCH_TIME_SUCCESS',
    FETCH_TIME_FAILURE: 'FETCH_TIME_FAILURE',

    FETCH_NEXT_DATES_START: 'FETCH_NEXT_DATES_START',
    FETCH_NEXT_DATES_SUCCESS: 'FETCH_NEXT_DATES_SUCCESS',
    FETCH_NEXT_DATES_FAILURE: 'FETCH_NEXT_DATES_FAILURE'
};

export default appointmentActionTypes;
