const adminDataTypes = {
    FETCH_FILES_LIST_START: 'FETCH_FILES_LIST_START',
    FETCH_FILES_LIST_SUCCESS: 'FETCH_FILES_LIST_SUCCESS',
    FETCH_FILES_LIST_FAILURE: 'FETCH_FILES_LIST_FAILURE',

    FETCH_LAST_UPLOAD_START: 'FETCH_LAST_UPLOAD_START',
    FETCH_LAST_UPLOAD_SUCCESS: 'FETCH_LAST_UPLOAD_SUCCESS',
    FETCH_LAST_UPLOAD_FAILURE: 'FETCH_LAST_UPLOAD_FAILURE',

    EDIT_LAST_UPLOAD_START: 'EDIT_LAST_UPLOAD_START',
    EDIT_LAST_UPLOAD_SUCCESS: 'EDIT_LAST_UPLOAD_SUCCESS',
    EDIT_LAST_UPLOAD_FAILURE: 'EDIT_LAST_UPLOAD_FAILURE',


};

export default adminDataTypes;