const childActionTypes = {
    FETCH_CHILD_START: 'FETCH_CHILD_START',
    FETCH_CHILD_SUCCESS: 'FETCH_CHILD_SUCCESS',
    FETCH_CHILD_FAILURE: 'FETCH_CHILD_FAILURE'
};

export default childActionTypes;
