const municipalityActionTypes = {
    FETCH_MUNICIPALITIES_START: 'FETCH_MUNICIPALITIES_START',
    FETCH_MUNICIPALITIES_SUCCESS: 'FETCH_MUNICIPALITIES_SUCCESS',
    FETCH_MUNICIPALITIES_FAILURE: 'FETCH_MUNICIPALITIES_FAILURE',
    FETCH_MUNICIPALITY_OPTIONS_START: 'FETCH_MUNICIPALITY_OPTIONS_START',
    FETCH_MUNICIPALITY_OPTIONS_SUCCESS: 'FETCH_MUNICIPALITY_OPTIONS_SUCCESS',
    FETCH_MUNICIPALITY_OPTIONS_FAILURE: 'FETCH_MUNICIPALITY_OPTIONS_FAILURE'
};

export default municipalityActionTypes;
