const documentsActionTypes = {
    FETCH_INTERNATIONAL_LAWS_START: 'FETCH_INTERNATIONAL_LAWS_START',
    FETCH_INTERNATIONAL_LAWS_SUCCESS: 'FETCH_INTERNATIONAL_LAWS_SUCCESS',
    FETCH_INTERNATIONAL_LAWS_FAILURE: 'FETCH_INTERNATIONAL_LAWS_FAILURE',
};

export default documentsActionTypes;
